### ISSUE TITLE
Conversation.json missing

### ISSUE THREAD

**Issue by nbckr** [IBM/vr-speech-sandbox-vive#3]
Hi there. Very cool project. I got a 404 though when following [the link to Conversation.json](https://github.com/IBM/vr-speech-sandbox-vive/blob/master/Conversation.json) and also couldn't manually find the file.

**Comment by stevemart** [comment]
hey @nbckr we're moving a few things around still, everything should be ready on 5/1/2017, but for now the conversation.json was moved to https://github.com/IBM/vr-speech-sandbox-vive/blob/master/data/workspace.json

**Comment by stevemart** [comment]
See https://github.com/IBM/vr-speech-sandbox-vive/commit/16239eaa19f0809f699377f05e91cdb765310458 for a fix to the readme
