### ISSUE TITLE
Remove acronyms

### ISSUE THREAD

**Issue by germanattanasio** [IBM/vr-speech-sandbox-vive#4]
I think the project should be renamed to `watson-visual-recognition-speech-sandbox-vive`.
We should not use acronyms to refer to our services.

**Comment by scottdangelo** [comment]
In this case, the VR refers to Virtual Reality.

**Comment by germanattanasio** [comment]
There you have a case where acronyms are a bad idea.

**Comment by Perefin** [comment]
The only place "VR" isn't Virtual Reality is IBM, just FYI - it's universally known and accepted as far as I have seen

**Comment by germanattanasio** [comment]
@Perefin I just google "vr" and 99.99% of the results were related to Virtual Reality so I'm going to close this issue.
