### ISSUE TITLE
A tree couldn't be loaded because the prefab is missing.

### ISSUE THREAD

**Issue by scottdangelo** [IBM/vr-speech-sandbox-vive#4]
I receive this error when I build and run:
A tree couldn't be loaded because the prefab is missing.

**Comment by scottdangelo** [comment]
Looks like tree2 is missing from Assets/Prefabs/CreatableObjects

**Comment by craigkj312** [comment]
The terrain in the game had old tree prefabs attached which are no longer part of it. I simply removed the missing tree prefabs from the terrain object as they weren't being used anyway.
