### ISSUE TITLE
VoiceSpawner compile error

### ISSUE THREAD

**Issue by jcorvinus** [IBM/vr-speech-sandbox-vive#9]
I got to step 3, sub-step 5 in the instructions [here](https://github.com/IBM/vr-speech-sandbox-vive). After copying the SDK into the assets folder and re-naming it, I ran into a compile error. See below:

Assets/Scripts/VoiceSpawner.cs(59,40): error CS0123: A method or delegate `VoiceSpawner.OnMessage(IBM.Watson.DeveloperCloud.Services.Conversation.v1.MessageResponse, string)' parameters do not match delegate `IBM.Watson.DeveloperCloud.Services.Conversation.v1.Conversation.OnMessage(object, string)' parameters

using Unity 5.6.0p3. My guess is that the sandbox got broken by an SDK update.

**Comment by scottdangelo** [comment]
Yes, I've fix in this branch: https://github.com/IBM/vr-speech-sandbox-vive/pull/8
I should have that merged into the master branch today.

**Comment by scottdangelo** [comment]
Fix has been merged into master branch. Note that it is different from the original patch, so please pick up the final version from master.
